### ISSUE TITLE
Icon problem when using dual screen

### ISSUE THREAD

**Issue by barthmania** [lukas-kurka/synology-drive-icons#1]
Hi,

The icon size and factor is changing on one display when using the other display.

Do you know know how to fix this please ?

Thank you in advance.

**Comment by lukas-kurka** [comment]
Hi, I have noticed that as well when I use two displays. I suspect this is internal issue of Drive Client, can't see how it could be connected to these custom icons. However after updating to 3.0.1 the problem seems to be gone.

**Comment by barthmania** [comment]
Yes you are right, it actually also happens with the original icons.

I also updated to 3.0.1 but still have the issue.

Thanks for your reply.
